KIT-4553 Introduce Ruff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,15 +23,16 @@ jobs:
           python-version: "3.12"
       - name: Add linting matchers
         run: |
-          echo "::add-matcher::.github/flake8-error-problem-matcher.json"
-          echo "::add-matcher::.github/flake8-warning-problem-matcher.json"
           echo "::add-matcher::.github/mypy-error-problem-matcher.json"
-      - name: Lint
-        uses: py-actions/flake8@v2
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements-dev.txt
+      - name: Create ruff failures dir
+        run: mkdir -p ./ruff_failures
+      - name: Lint with ruff
+        run: |
+          ruff check --output-format github . || echo "sag_py_auth" >> ./ruff_failures/ruff_failures.txt
       - name: Lint typing
         # Must run with installed dependencies
         run: |
